// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpsjlkmiajhxkxrzgjrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwc2psa21pYWpoeGt4cnpnanJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTUxMTEsImV4cCI6MjA3NTY3MTExMX0.NxYaPO3PeWbX0jEhhZ9N-b3RVHCK3_35dR-eeJJUi1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});